version: "3.8"
services:
  db:
    container_name: mysql-container
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - D:/config/docker/data/study/mysql:/var/lib/mysql
      #-/path-on-host-machine/scripts:/docker-entrypoint-initdb.d/
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    restart: always
    networks: 
      - study-network
  
  redis:
    container_name: redis-container
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - D:/config/docker/data/study/redis:/data
    command: redis-server --appendonly yes
    networks:
      - study-network
    depends_on:
      - db
      
  study:
    container_name: study-container
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
      - db
    networks: 
      - study-network
      
networks:
  study-network:
    driver: bridge